stages:
  - build
  - style

build-job:
  stage: build
  tags:
    - build
  script:
    - make -C src/cat
    - make -C src/grep
  artifacts:
    paths:
      - src/cat/s21_cat
      - src/grep/s21_grep
    expire_in: 30 days
  only:
    - develop

style-job:
  stage: style
  tags:
    - style
  script:
    - clang-format -style=Google -Werror -n src/cat/s21_cat.* src/grep/s21_grep.*
  only:
    - develop