stages:
  - build
  - style
  - test
  - deploy

build-job:
  stage: build
  tags:
    - build
  script:
    - make -C src/cat
    - make -C src/grep
  artifacts:
    paths:
      - src/cat/s21_cat
      - src/grep/s21_grep
    expire_in: 30 days
  only:
    - develop

style-job:
  stage: style
  tags:
    - style
  script:
    - clang-format -style=Google -Werror -n src/cat/s21_cat.* src/grep/s21_grep.*
  only:
    - develop

test-job:
  stage: test
  tags:
    - test
  when: on_success
  script:
    - cd src
    - cd cat && bash run_tests.sh
    - cd ../grep && bash run_tests.sh
  
  only:
    - develop

# deploy-job:
#   stage: deploy
#   tags:
#     - deploy
#   needs:
#     - build-job
#     - style-job
#     - test-job
#   when: manual
#   script:
#     - bash src/deploy.sh
#   only:
#     - develop